name: Test OIDC

on:
  workflow_dispatch:

env:
  PROJECT_ID: cust-b-dev-bb-project-x1
  PROJECT_NO: 545072476622
  
jobs:
  authenticate:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          workload_identity_provider: 'projects/545072476622/locations/global/workloadIdentityPools/cust-b-dev-bb-project-x1-idn-pl/providers/gh-provider'
          service_account: 'bb-project-x1-cicd@cust-b-dev-bb-project-x1.iam.gserviceaccount.com'
          
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
          
      - name: get SA list
        run: |
          gcloud iam service-accounts list

